// Art direction, not fixed drawings or preselected discovery references.
const nonAquatic = ['Escenas submarinas', 'Peces', 'Burbujas acuáticas', 'Gotas de agua como motivo central'];
const familySource = 'https://frutiger-aero.org/frutiger-aero';
const profiles = [
  {id:'outline-rounded',name:'Outline redondeado · MusicArt',aliases:['Rounded outline','Monoline redondeado','MusicArt'],family:'Iconos de interfaz',cues:['Contornos sin relleno, un solo color #2F5148 y grosor uniforme de 1.2 px sobre retícula de 24 (equivale a 2.4 unidades sobre retícula de 48)','Puntas y uniones redondas; curvas suaves, silueta clara y partes semánticas editables','Compartir proporciones ópticas y espaciado entre instrumentos; conservar solo rasgos que se lean a 24 y 32 px','El host adapta el color monocromático al tema: #2F5148 sobre claro, #BFD6C4 sobre oscuro, sin cambiar geometría'],avoid:['Placas de app, fondos o contenedores decorativos','Volúmenes rellenos, gradientes, brillos, sombras, texturas y transparencias en el trazo','Cuerdas y mecanismos diminutos que se fusionan al reducir'],note:'Familia de controles MusicArt: lineal, monocromática y sin relieve. El fondo pertenece a la interfaz.',sources:[]},
  {"id": "material-3", "name": "Material 3 tonal", "aliases": ["Material 3", "Material You"], "family": "Sistema de diseño", "cues": ["Formas claras, esquinas suaves y jerarquía tonal", "Paleta coordinada con buen contraste; evitar relieve por defecto"], "avoid": ["Detalles ilegibles a 24 px", "Pérdida de la función del producto"], "note": "Dirección visual ARU; la generación debe verificar su coherencia.", "sources": []},
  {"id": "material-3-expressive", "name": "Material 3 Expressive", "aliases": [], "family": "Sistema de diseño", "cues": ["Formas más expresivas y variación controlada de siluetas", "Color tonal, acentos vivos y legibilidad a tamaño pequeño"], "avoid": ["Detalles ilegibles a 24 px", "Pérdida de la función del producto"], "note": "Dirección visual ARU; la generación debe verificar su coherencia.", "sources": []},
  {"id": "apple-minimal", "name": "Apple minimalista", "aliases": ["Apple", "Apple minimal"], "family": "Sistema de diseño", "cues": ["Silueta equilibrada, curvas limpias y espacio generoso", "Detalles mínimos y coherencia óptica; evitar adornos gratuitos"], "avoid": ["Detalles ilegibles a 24 px", "Pérdida de la función del producto"], "note": "Dirección visual ARU; la generación debe verificar su coherencia.", "sources": []},
  {"id": "monochrome", "name": "Minimalista monocromático", "aliases": ["Monocromático"], "family": "Minimalismo", "cues": ["Un color principal, contraste claro y trazos coherentes", "Iconos reconocibles sin depender de textura"], "avoid": ["Detalles ilegibles a 24 px", "Pérdida de la función del producto"], "note": "Dirección visual ARU; la generación debe verificar su coherencia.", "sources": []},
  {"id": "liquid-glass", "name": "Cristal / Liquid Glass", "aliases": ["Liquid Glass", "Cristal"], "family": "Cristal", "cues": ["Superficie pulida, reflejos discretos y profundidad", "Conservar el símbolo nítido y fondo opaco"], "avoid": ["Detalles ilegibles a 24 px", "Pérdida de la función del producto"], "note": "Dirección visual ARU; la generación debe verificar su coherencia.", "sources": []},
  {"id": "futuristic-minimal", "name": "Futurista minimalista", "aliases": [], "family": "Minimalismo", "cues": ["Geometría precisa, siluetas compactas y pocos acentos", "Evitar el exceso de detalles tecnológicos"], "avoid": ["Detalles ilegibles a 24 px", "Pérdida de la función del producto"], "note": "Dirección visual ARU; la generación debe verificar su coherencia.", "sources": []},
  {"id": "clay", "name": "Clay / relieve suave", "aliases": ["Clay"], "family": "Relieve", "cues": ["Volumen mate y formas compactas redondeadas", "Sombras contenidas y contornos legibles"], "avoid": ["Detalles ilegibles a 24 px", "Pérdida de la función del producto"], "note": "Dirección visual ARU; la generación debe verificar su coherencia.", "sources": []},
  {"id": "cyberpunk", "name": "Cyberpunk / neón", "aliases": ["Cyberpunk", "Neón"], "family": "Futurismo", "cues": ["Acentos luminosos y contraste oscuro", "Mantener el símbolo claro sin halos que tapen el contorno"], "avoid": ["Detalles ilegibles a 24 px", "Pérdida de la función del producto"], "note": "Dirección visual ARU; la generación debe verificar su coherencia.", "sources": []},
  {"id": "memphis", "name": "Memphis retro", "aliases": ["Memphis"], "family": "Gráfica retro", "cues": ["Geometría lúdica, colores contrastantes y ritmo gráfico", "Pocos elementos que sobrevivan a 24 px"], "avoid": ["Detalles ilegibles a 24 px", "Pérdida de la función del producto"], "note": "Dirección visual ARU; la generación debe verificar su coherencia.", "sources": []},
  {"id": "y2k-chrome", "name": "Y2K cromado", "aliases": ["Y2K"], "family": "Retro tecnológico", "cues": ["Siluetas dinámicas y metal pulido de los 2000", "Reflejos concentrados y un símbolo claramente ligado a la app"], "avoid": ["Detalles ilegibles a 24 px", "Pérdida de la función del producto"], "note": "Dirección visual ARU; la generación debe verificar su coherencia.", "sources": []},
  {"id": "skeuomorphic", "name": "Esqueumórfico", "aliases": ["Skeuomorfismo"], "family": "Objetos físicos", "cues": ["Representar objetos funcionales con volumen y materiales", "Detalles útiles y legibles, sin decoración ajena al propósito"], "avoid": ["Detalles ilegibles a 24 px", "Pérdida de la función del producto"], "note": "Dirección visual ARU; la generación debe verificar su coherencia.", "sources": []},
  {"id": "pop-cartoon", "name": "Pop / cartoon / slime", "aliases": ["Pop", "Cartoon", "Slime"], "family": "Pop", "cues": ["Formas orgánicas, trazos expresivos y colores vivos", "Usar personajes o slime solo si ayudan al concepto"], "avoid": ["Detalles ilegibles a 24 px", "Pérdida de la función del producto"], "note": "Dirección visual ARU; la generación debe verificar su coherencia.", "sources": []},
  {id:'frutiger-aero',name:'Frutiger Aero · sin aqua',aliases:['Frutiger Aero','Frutiger'],family:'Frutiger',cues:['Brillo de interfaces y productos de los 2000','Volumen, biseles y gradientes limpios','Investigar Dark Aero, Aurora, Eco, Fruits o DORFic y elegir una dirección pertinente para el producto'],avoid:nonAquatic,note:'Familia amplia: declarar la variante elegida en el breve. No asumir que significa agua.',sources:[familySource]},
  {id:'dark-aero',name:'Dark Aero',aliases:['Frutiger Dark','Frutiger Aero Dark'],family:'Frutiger',cues:['Negro piano, grafito y vidrio ahumado','Brillos de borde y reflejos controlados','Acentos luminosos sobre una silueta fuerte'],avoid:[...nonAquatic,'Convertirlo en cyberpunk genérico'],note:'Etiqueta comunitaria; el perfil excluye aqua por preferencia del proyecto.',sources:['https://frutiger-aero.org/dark-aero']},
  {id:'frutiger-fruits',name:'Frutiger Fruits',aliases:['Frutiger Fruit','Frutiger fruit','Fruity Aero'],family:'Frutiger',cues:['Colores cítricos y frutales saturados','Superficies pulidas con sensación de frescura','Formas orgánicas compactas y translúcidas'],avoid:[...nonAquatic,'Añadir una fruta literal si contradice la función de la app'],note:'Nombre comunitario informal. Se utiliza como dirección frutal, no como norma de diseño.',sources:['https://note.com/death_4sei/n/ne64dcdbf98ae?hl=en']},
  {id:'frutiger-aurora',name:'Frutiger Aurora',aliases:['Aurora Aero'],family:'Frutiger',cues:['Bandas de luz y auroras','Gradientes violeta, azul y verde','Cristal luminoso y profundidad suave'],avoid:[...nonAquatic,'Llenar el icono de estrellas y ruido'],note:'Dirección luminosa y abstracta dentro de la familia.',sources:[familySource]},
  {id:'frutiger-eco',name:'Frutiger Eco',aliases:['Eco Aero'],family:'Frutiger',cues:['Naturaleza y tecnología limpia','Verde, blanco, hojas y superficies brillantes','Metáfora del producto por encima del decorado natural'],avoid:[...nonAquatic,'Usar una hoja genérica para cualquier producto'],note:'Afinidad con Frutiger; variantes definidas como guías prácticas.',sources:[familySource]},
  {id:'dorfic',name:'DORFic',aliases:['DORFic'],family:'Frutiger / Abstract Tech',cues:['Naranja, blanco y luz diurna','Geometría tecnológica y sensación optimista','Profundidad limpia con detalles de interfaz'],avoid:[...nonAquatic,'Confundirlo con una escena nocturna de neón'],note:'Familia relacionada, no sinónimo de todo Frutiger Aero.',sources:[familySource]},
  {id:'frutiger-metro',name:'Frutiger Metro',aliases:['Vector Metro','Flat Frutiger Aero'],family:'Frutiger / gráfica vectorial',cues:['Formas vectoriales, curvas y composiciones dinámicas','Paletas vivas y siluetas recortadas','Ritmo gráfico con pocos elementos legibles'],avoid:[...nonAquatic,'Confundirlo con el dashboard Metro de Xbox de 2011','Aplicar vidrio 3D por defecto'],note:'Etiqueta estética diferente del nombre de una interfaz Metro.',sources:['https://frutiger-aero.org/frutiger-metro']},
  {id:'funky-seasons',name:'Funky Seasons / Four Colors',aliases:['Funky Seasons','Four Colors','Four Colours'],family:'Superflat Pop / Frutiger relacionado',cues:['Verde lima, azul cielo, rosa intenso y naranja vivo','Siluetas claras y energía pop','Color como identidad: considerar variantes del mismo símbolo, sin exigir los cuatro colores en un único icono'],avoid:[...nonAquatic,'Confundirlo con slime','Sustituir la identidad por manchas de cuatro colores'],note:'Guía de paleta y lenguaje pop; las cuatro variantes son opcionales, no una operación automática.',sources:['https://2000-aesthetics.fandom.com/wiki/Funky_Seasons']},
  {id:'skeuomorphic-scifi',name:'Sci-fi industrial skeuomorfo',aliases:['Sci-fi industrial','Skeuomorphic sci-fi','Hardware sci-fi'],family:'Perfil ARU de hardware',cues:['Carcasa, piezas ensambladas y biseles','Materiales de metal o plástico con volumen','Pantalla luminosa y controles físicos legibles'],avoid:['Copiar armaduras, logos o símbolos de Halo','Añadir controles diminutos que se pierden a 24 px'],note:'Descripción visual para skins como Halo 2 WMP, no nombre histórico oficial de una subestética.',sources:['https://www.theskinsfactory.com/uiux-design-blog/the-origin-of-a-ux-design-studio2']},
  {id:'console-gloss',name:'Console gloss · Blades / NXE',aliases:['Xbox Blades','Blades','Xbox NXE','NXE'],family:'Perfil ARU de interfaces de consola',cues:['Paneles curvos y plástico pulido','Pestañas con profundidad para Blades; tarjetas en perspectiva para NXE','Acentos verdes o cálidos y navegación visual clara'],avoid:[...nonAquatic,'Mezclar Blades, NXE y el dashboard Metro como si fueran la misma interfaz','Copiar el logo Xbox'],note:'Perfil práctico inspirado en interfaces concretas; sus nombres históricos se mantienen separados.',sources:['https://news.xbox.com/en-us/2008/07/14/some-of-the-features-in-the-new-xbox-experience-8-person-chat-vga-plus-more/']},
];
const normalized = s => String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[\s_-]+/g,' ').trim();
export function listStyles(){return structuredClone(profiles);}
export function resolveStyle(style){
  const key=normalized(style),p=profiles.find(p=>[p.id,p.name,...p.aliases].some(x=>normalized(x)===key));
  if(!p)return null;
  const {sources,aliases,...guidance}=structuredClone(p);
  // Documentation sources are not research evidence and must not be injected as discovered references.
  return {...guidance,requested:style};
}
