// Art direction, not fixed drawings or preselected discovery references.
const nonAquatic = ['Escenas submarinas', 'Peces', 'Burbujas acuáticas', 'Gotas de agua como motivo central'];
const familySource = 'https://frutiger-aero.org/frutiger-aero';
const profiles = [
  {id:'frutiger-aero',name:'Frutiger Aero · sin aqua',aliases:['Frutiger Aero','Frutiger'],family:'Frutiger',cues:['Brillo de interfaces y productos de los 2000','Volumen, biseles y gradientes limpios','Investigar Dark Aero, Aurora, Eco, Fruits o DORFic y elegir una dirección pertinente para el producto'],avoid:nonAquatic,note:'Familia amplia: declarar la variante elegida en el breve. No asumir que significa agua.',sources:[familySource]},
  {id:'dark-aero',name:'Dark Aero',aliases:['Frutiger Dark','Frutiger Aero Dark'],family:'Frutiger',cues:['Negro piano, grafito y vidrio ahumado','Brillos de borde y reflejos controlados','Acentos luminosos sobre una silueta fuerte'],avoid:[...nonAquatic,'Convertirlo en cyberpunk genérico'],note:'Etiqueta comunitaria; el perfil excluye aqua por preferencia del proyecto.',sources:['https://frutiger-aero.org/dark-aero']},
  {id:'frutiger-fruits',name:'Frutiger Fruits',aliases:['Frutiger Fruit','Frutiger fruit','Fruity Aero'],family:'Frutiger',cues:['Colores cítricos y frutales saturados','Superficies pulidas con sensación de frescura','Formas orgánicas compactas y translúcidas'],avoid:[...nonAquatic,'Añadir una fruta literal si contradice la función de la app'],note:'Nombre comunitario informal. Se utiliza como dirección frutal, no como norma de diseño.',sources:['https://note.com/death_4sei/n/ne64dcdbf98ae?hl=en']},
  {id:'frutiger-aurora',name:'Frutiger Aurora',aliases:['Aurora Aero'],family:'Frutiger',cues:['Bandas de luz y auroras','Gradientes violeta, azul y verde','Cristal luminoso y profundidad suave'],avoid:[...nonAquatic,'Llenar el icono de estrellas y ruido'],note:'Dirección luminosa y abstracta dentro de la familia.',sources:[familySource]},
  {id:'frutiger-eco',name:'Frutiger Eco',aliases:['Eco Aero'],family:'Frutiger',cues:['Naturaleza y tecnología limpia','Verde, blanco, hojas y superficies brillantes','Metáfora del producto por encima del decorado natural'],avoid:[...nonAquatic,'Usar una hoja genérica para cualquier producto'],note:'Afinidad con Frutiger; variantes definidas como guías prácticas.',sources:[familySource]},
  {id:'dorfic',name:'DORFic',aliases:['DORFic'],family:'Frutiger / Abstract Tech',cues:['Naranja, blanco y luz diurna','Geometría tecnológica y sensación optimista','Profundidad limpia con detalles de interfaz'],avoid:[...nonAquatic,'Confundirlo con una escena nocturna de neón'],note:'Familia relacionada, no sinónimo de todo Frutiger Aero.',sources:[familySource]},
  {id:'frutiger-metro',name:'Frutiger Metro',aliases:['Vector Metro','Flat Frutiger Aero'],family:'Frutiger / gráfica vectorial',cues:['Formas vectoriales, curvas y composiciones dinámicas','Paletas vivas y siluetas recortadas','Ritmo gráfico con pocos elementos legibles'],avoid:[...nonAquatic,'Confundirlo con el dashboard Metro de Xbox de 2011','Aplicar vidrio 3D por defecto'],note:'Etiqueta estética diferente del nombre de una interfaz Metro.',sources:['https://frutiger-aero.org/frutiger-metro']},
  {id:'funky-seasons',name:'Funky Seasons / Four Colors',aliases:['Funky Seasons','Four Colors','Four Colours'],family:'Superflat Pop / Frutiger relacionado',cues:['Verde lima, azul cielo, rosa intenso y naranja vivo','Siluetas claras y energía pop','Color como identidad: considerar variantes del mismo símbolo, sin exigir los cuatro colores en un único icono'],avoid:[...nonAquatic,'Confundirlo con slime','Sustituir la identidad por manchas de cuatro colores'],note:'Guía de paleta y lenguaje pop; las cuatro variantes son opcionales, no una operación automática.',sources:['https://2000-aesthetics.fandom.com/wiki/Funky_Seasons']},
  {id:'skeuomorphic-scifi',name:'Sci-fi industrial skeuomorfo',aliases:['Sci-fi industrial','Skeuomorphic sci-fi','Hardware sci-fi'],family:'Perfil ARU de hardware',cues:['Carcasa, piezas ensambladas y biseles','Materiales de metal o plástico con volumen','Pantalla luminosa y controles físicos legibles'],avoid:['Copiar armaduras, logos o símbolos de Halo','Añadir controles diminutos que se pierden a 24 px'],note:'Descripción visual para skins como Halo 2 WMP, no nombre histórico oficial de una subestética.',sources:['https://www.theskinsfactory.com/uiux-design-blog/the-origin-of-a-ux-design-studio2']},
  {id:'console-gloss',name:'Console gloss · Blades / NXE',aliases:['Xbox Blades','Blades','Xbox NXE','NXE'],family:'Perfil ARU de interfaces de consola',cues:['Paneles curvos y plástico pulido','Pestañas con profundidad para Blades; tarjetas en perspectiva para NXE','Acentos verdes o cálidos y navegación visual clara'],avoid:[...nonAquatic,'Mezclar Blades, NXE y el dashboard Metro como si fueran la misma interfaz','Copiar el logo Xbox'],note:'Perfil práctico inspirado en interfaces concretas; sus nombres históricos se mantienen separados.',sources:['https://news.xbox.com/en-us/2008/07/14/some-of-the-features-in-the-new-xbox-experience-8-person-chat-vga-plus-more/']},
];
const normalized = s => String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[\s_-]+/g,' ').trim();
export function listStyles(){return structuredClone(profiles);}
export function resolveStyle(style){
  const key=normalized(style),p=profiles.find(p=>[p.id,p.name,...p.aliases].some(x=>normalized(x)===key));
  if(!p)return null;
  const {sources,aliases,...guidance}=structuredClone(p);
  // Documentation sources are not research evidence and must not be injected as discovered references.
  return {...guidance,requested:style};
}
