import {listMaterials,prepareIconExports} from '../plugin/index.js';
const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const descriptions={neon:'Luz & resplandor',chrome:'Metal & reflejos',glass:'Cristal tintado',clay:'Volumen mate',fruits:'Gel & color'};
export function renderMaterialGallery(base,group='iconos_app_2') {
 const materials=listMaterials(),icons=prepareIconExports(base,{group}).entries;
 return `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Materiales · ARU Studio</title><link rel="stylesheet" href="../../src/material-gallery.css"></head>
<body data-group="${esc(group)}">
<nav class="masthead" aria-label="Navegación principal"><a class="wordmark" href="../../index.html"><span class="brand-mark" aria-hidden="true">a</span>aru <small>STUDIO</small></a><div><a href="#collection">Colección</a><a href="#workbench">Mesa de trabajo</a></div><a class="download-all" href="cinco-materiales.zip" download>Descargar colección <span aria-hidden="true">↓</span></a></nav>
<main>
<header class="intro"><div class="eyebrow">ESTUDIO DE MATERIALES <span>01 — CATART</span></div><div class="intro-line"><h1>Una base.<br><em>Cinco acabados.</em></h1><div class="intro-note"><p>La misma familia, otra expresión.<br>Explora el material sin perder el trazo.</p><a href="#workbench">Llévalo a tu mesa <span aria-hidden="true">↗</span></a></div></div></header>
<div class="material-shelf" aria-label="Elegir material">${materials.map((m,i)=>`<button class="material-card${i===0?' active':''}" data-material="${m.id}" aria-pressed="${i===0}" aria-label="${esc(m.label)}"><span class="material-index">0${i+1}</span><img src="${m.id}-surface.png" alt="" width="192" height="192"><span class="material-caption"><strong>${esc(m.label)}</strong><span class="material-check" aria-hidden="true">↗</span></span><span class="material-note">${descriptions[m.id]}</span></button>`).join('')}</div>
<section id="collection" class="collection" aria-labelledby="collection-title"><div class="section-top"><div><span class="eyebrow">LA FAMILIA</span><h2 id="collection-title">CatArt <span>50 iconos</span></h2></div><div class="view-controls"><button id="show-base" aria-pressed="false">Ver base</button><div class="size-controls" aria-label="Tamaño de vista previa">${[24,48,96].map(size=>`<button data-size="${size}" aria-pressed="${size===48}">${size} px</button>`).join('')}</div></div></div>
<div class="collection-meta"><span id="current-material">Neón · Luz & resplandor</span><span>Vista al tamaño real</span></div>
<div class="icon-grid" data-current="neon" style="--tile:#191426;--preview:48px">${icons.map((e,i)=>`<a class="icon-tile" href="neon/${esc(e.name)}-48.png" download data-icon="${esc(e.name)}"><span class="icon-number">${String(i+1).padStart(2,'0')}</span><div class="icon-art"><img src="neon/${esc(e.name)}-48.png" width="48" height="48" alt="${esc(e.label)}" loading="lazy"></div><span class="icon-name">${esc(e.label)}</span><span class="icon-download" aria-hidden="true">↓</span></a>`).join('')}</div>
<div class="collection-export"><div><strong>Listos para salir del estudio.</strong><p>PNG a 24, 48 y 96 px · SVG · ARU editable</p></div><div class="export-actions"><a id="download-source" href="neon.aru" download>Base editable ↗</a><a id="download-material" class="solid-button" href="neon-50.zip" download>Descargar Neón <span aria-hidden="true">↓</span></a></div></div></section>
<section id="workbench" class="workbench" aria-labelledby="workbench-title"><div class="section-top"><div><span class="eyebrow">HAZLO TUYO</span><h2 id="workbench-title">Mesa de trabajo</h2></div><p>Una copia de la base, lista para experimentar.</p></div><div class="bench-controls"><label for="material">Acabado</label><select id="material">${materials.map(m=>`<option value="${m.id}">${esc(m.label)}</option>`).join('')}</select><button id="apply" class="solid-button" disabled>Aplicar a la selección</button><button id="undo" disabled>Deshacer</button><span id="status" role="status" aria-live="polite">Preparando el lienzo…</span></div><div id="editor"></div></section>
<footer class="colophon"><span>ARU STUDIO <span class="footer-rule">/</span> Hecho para seguir editando.</span><details><summary>Notas del estudio</summary><p>Los acabados son pintura y efectos 2D. Las formas se conservan; a 24 px algunos reflejos pierden detalle. Cristal y Cromado se distinguen mejor en superficies rellenas.</p><p>La placa de gato es un control adicional de superficie. Los PNG tienen fondo opaco; las bases mantienen sus huecos editables.</p><a href="RESULTADOS.md">Resultados de la prueba ↗</a> <a href="verification.json">Verificación técnica ↗</a></details></footer>
</main><script type="module" src="../../src/material-gallery.js"></script></body></html>`;
}
