// CLI: node tools/metrics.mjs examples/cat-on-rock.aru [--svg out/cat.svg]
import fs from 'node:fs';
import zlib from 'node:zlib';
import { compile } from '../src/engine.js';
import { renderScene } from '../src/render.js';
import { toAru } from '../src/serialize.js';
import { sceneMetrics, textMetrics, svgMetrics, aruReadability, semanticMetrics } from '../src/metrics.js';

const file = process.argv[2] || 'examples/cat-on-rock.aru';
const svgOut = process.argv.includes('--svg') ? process.argv[process.argv.indexOf('--svg') + 1] : null;
const src = fs.readFileSync(file, 'utf8');

// warm up + measure best of 5 to avoid JIT noise
let r; const times = [];
for (let i = 0; i < 5; i++) { r = compile(src); times.push(r.timings); }
const best = (k) => Math.min(...times.map((t) => t[k] ?? Infinity));

if (!r.ok) { console.error('ERRORS:'); for (const e of r.errors) console.error(` line ${e.line}: ${e.message}`); }
for (const w of r.warnings) console.error(` warning line ${w.line}: ${w.message}`);

const svg = renderScene(r.scene, { pretty: true, dataAttrs: false });
const svgOpt = renderScene(r.scene, { pretty: true, dataAttrs: false, dedupe: true, precision: 2 });
if (svgOut) { fs.writeFileSync(svgOut, svg); fs.writeFileSync(svgOut.replace(/\.svg$/, '.optimized.svg'), svgOpt); }
const flatAru = toAru(r.scene);
const fa2 = textMetrics(toAru(r.scene, { precision: 2 }));
if (svgOut) fs.writeFileSync(svgOut.replace(/\.svg$/, '.flat.aru'), flatAru);
const fa = textMetrics(flatAru);
const sm = sceneMetrics(r.scene), tm = textMetrics(src), ar = aruReadability(src), sv = svgMetrics(svg), so = svgMetrics(svgOpt);
const json = { file, scene: sm, aru: { ...tm, ...ar }, aruFlat: fa, svgFlat: sv, svgOptimized: so, timings: { parse: best('parse'), scene: best('scene'), render: best('render') } };


const pad = (s, n) => String(s).padStart(n);
console.log(`\n== ${file} ==`);
console.log(`objects total ${sm.objects}: written in source ${sm.source}, expanded by repeat/clone ${sm.expanded}, generated by fur/ridge ${sm.generated}; groups ${sm.groups}, explicitly named ${sm.named}, max depth ${sm.maxDepth}`);
console.log(`paths ${sm.paths}, points ${sm.points}, bezier curves ${sm.beziers}`);
console.log(`shapes: ${Object.entries(sm.shapes).map(([k, v]) => `${k} ${v}`).join(', ')}`);
console.log(`file: ${tm.lines} lines, ${tm.chars} chars, ${tm.bytes} bytes, ~${tm.tokens} tokens (chars/4 = ${tm.charsPer4}, lexer tokens ${r.tokenCount})`);
console.log(`timings (best of 5): parse ${best('parse').toFixed(2)} ms, scene ${best('scene').toFixed(2)} ms, render ${best('render').toFixed(2)} ms`);
console.log(`\n== ARU vs SVG ==`);
console.log(`${pad('', 22)}${pad('ARU', 10)}${pad('SVG flat', 10)}${pad('ratio', 8)}${pad('SVG opt', 10)}${pad('ratio', 8)}`);
const rt = (a, b) => (typeof a === 'number' && a ? (b / a).toFixed(1) + 'x' : '');
const row = (k, a, b, c) => console.log(`${pad(k, 22)}${pad(a, 10)}${pad(b, 10)}${pad(rt(a, b), 8)}${pad(c, 10)}${pad(rt(a, c), 8)}`);
row('bytes', tm.bytes, sv.bytes, so.bytes); row('chars', tm.chars, sv.chars, so.chars); row('lines', tm.lines, sv.lines, so.lines);
row('tokens (approx)', tm.tokens, sv.tokens, so.tokens); row('chars/4', tm.charsPer4, sv.charsPer4, so.charsPer4);
row('nodes/elements', sm.objects, sv.nodes, so.nodes); row('numeric literals', ar.numbers, sv.numbers, so.numbers);
row('numeric share', (ar.numericShare * 100).toFixed(0) + '%', (sv.numericShare * 100).toFixed(0) + '%', (so.numericShare * 100).toFixed(0) + '%');
row('named objects', sm.named, 0, 0);
const gz = (t) => zlib.gzipSync(Buffer.from(t)).length;
row('gzip bytes', gz(src), gz(svg), gz(svgOpt));
if (svgOut) console.log(`\nSVG written to ${svgOut}`);

console.log(`\n== where does the gain come from? ==`);
console.log(`ARU as written          ${pad(tm.tokens, 7)} tokens  ${pad(tm.bytes, 8)} bytes`);
console.log(`ARU flat (expanded)     ${pad(fa2.tokens, 7)} tokens  ${pad(fa2.bytes, 8)} bytes   <- same scene, no repeat/clone/fur`);
const flatNoNames = toAru(r.scene, { keepNames: false, precision: 2 });
const fan = textMetrics(flatNoNames);
if (svgOut) { fs.writeFileSync(svgOut.replace(/\.svg$/, '.flat-nonames.aru'), flatNoNames); fs.writeFileSync(svgOut.replace(/\.svg$/, '.flat2.aru'), toAru(r.scene, { precision: 2 })); }
json.aruFlatNoNames = fan;
console.log(`ARU flat, no names      ${pad(fan.tokens, 7)} tokens  ${pad(fan.bytes, 8)} bytes   <- pure syntax, same information as SVG`);
console.log(`SVG flat                ${pad(sv.tokens, 7)} tokens  ${pad(sv.bytes, 8)} bytes`);
console.log(`syntax gain (SVG flat / ARU flat no names) ${(sv.tokens / fan.tokens).toFixed(2)}x tokens, ${(sv.bytes / fan.bytes).toFixed(2)}x bytes`);
console.log(`generative gain (ARU flat / ARU written) ${(fa2.tokens / tm.tokens).toFixed(2)}x tokens`);
json.aruFlat = fa2;
// round-trip check: the flat ARU must rebuild the same picture
const r2 = compile(flatAru);
const svg2 = renderScene(r2.scene, { pretty: true, dataAttrs: false });
const numRe = /-?\d+(?:\.\d+)?/g;
const sameShape = svg.replace(numRe, '#') === svg2.replace(numRe, '#');
const n1 = svg.match(numRe) || [], n2 = svg2.match(numRe) || [];
const maxDelta = n1.length === n2.length ? Math.max(...n1.map((v, i) => Math.abs(v - n2[i]))) : Infinity;
console.log(`round-trip flat ARU -> SVG: same structure ${sameShape}, max numeric delta ${maxDelta.toFixed(3)} (rounding)${r2.errors.length ? ' (errors: ' + r2.errors.map((e) => e.message).slice(0, 3).join('; ') + ')' : ''}`);

for (const m of semanticMetrics(r.scene, src)) {
  console.log(`\n== semantic: blueprint ${m.name} ==`);
  const g = m.generated;
  const rows = [
    ['semantic instructions', m.instructions], ['landmarks', `${m.landmarks} (${m.landmarksAuthored} authored, rest mirrored)`], ['regions', m.regions],
    ['elements', `${m.elements} (${m.mirrored} mirror twins)`], ['procedural expansions', m.expansions],
    ['generated objects', g.objects], ['generated primitives', g.primitives], ['generated paths / polygons', `${g.paths} / ${g.polygons}`],
    ['generated Bézier curves', g.beziers], ['generated points', g.points], ['source lines (blueprint)', m.sourceLines], ['source tokens (blueprint)', m.sourceTokens],
    ['generated geometry tokens', m.geometryTokens], ['compile (resolve + procedural)', `${m.compileMs.toFixed(2)} ms`],
    ['EXPANSION tokens (geometry / source)', `${m.expansionTokens.toFixed(1)}x`], ['expansion primitives / instruction', m.expansionObjects.toFixed(2)], ['expansion points / instruction', (g.points / m.instructions).toFixed(1)],
  ];
  for (const [k, v] of rows) console.log(`${k.padStart(38)}  ${v}`);
  if (svgOut) fs.writeFileSync(svgOut.replace(/\.svg$/, `.${m.name}.geometry.aru`), m.geometryText);
  json.semantic = json.semantic || []; json.semantic.push({ ...m, geometryText: undefined });
}
if (process.argv.includes('--json')) fs.writeFileSync(process.argv[process.argv.indexOf('--json') + 1], JSON.stringify(json, null, 2));
