// Installs only the tarball in a clean consumer; validates the actual installed CLI and Node API.
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { spawnSync } from 'node:child_process';
import { pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';
const tarball = path.resolve(process.argv[2] || 'artifacts/fsaldivar.dev-aru-0.6.0.tgz');
const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'aru-packed-'));
await fs.writeFile(path.join(dir, 'package.json'), '{"private":true,"type":"module"}');
const installed = spawnSync('npm', ['install', '--no-audit', '--no-fund', tarball], { cwd: dir, encoding: 'utf8' });
if (installed.status) throw new Error(installed.stderr);
const pkg = path.join(dir, 'node_modules/@fsaldivar.dev/aru'), entry = path.join(pkg, 'bin/aru.mjs');
function cli(args, success = true, input) { const r = spawnSync(process.execPath, [entry, ...args], { cwd: dir, encoding: 'utf8', input }); assert.equal(r.status, success ? 0 : 1, r.stdout + r.stderr); return JSON.parse(r.stdout); }
const file = path.join(dir, 'doc.aru');
cli(['new', '--out', file]); cli(['new', '--out', file], false);
await fs.writeFile(file, 'canvas 320 240\nbackground #FFF\ngroup icono { circle ojo { at 100 100; radius 30; fill #333 } }');
const before = await fs.readFile(file, 'utf8'), ctx = cli(['context', file]);
assert.equal(ctx.layers.length, 2); assert(ctx.schema.properties.operations);
const ops = path.join(dir, 'ops.json'); await fs.writeFile(ops, JSON.stringify([{ op: 'set', target: 'icono.ojo', fill: '#3366FF' }]));
cli(['apply', file, '--ops', ops, '--dry-run']); assert.equal(await fs.readFile(file, 'utf8'), before);
cli(['preview', file, '--ops', ops, '--out', 'preview.svg']); assert.equal(await fs.readFile(file, 'utf8'), before);
cli(['apply', file, '--ops', ops, '--write', '--expected-hash', 'stale'], false); assert.equal(await fs.readFile(file, 'utf8'), before);
const bad = path.join(dir, 'bad.json'); await fs.writeFile(bad, JSON.stringify([{ op: 'set', target: 'icono.ojo', fill: '#F00' }, { op: 'invalid', target: 'icono' }]));
cli(['apply', file, '--ops', bad, '--write'], false); assert.equal(await fs.readFile(file, 'utf8'), before);
cli(['apply', file, '--ops', '-', '--write', '--expected-hash', ctx.hash], true, JSON.stringify([{ op: 'set', target: 'icono.ojo', fill: '#3366FF' }]));
cli(['render', file, '--out', 'result.png']);
const sharp = (await import(pathToFileURL(path.join(dir, 'node_modules/sharp/dist/index.mjs')))).default;
const { data, info } = await sharp(path.join(dir, 'result.png')).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
assert.equal(info.width, 320); for (let i = 3; i < data.length; i += 4) assert.equal(data[i], 255);
const core = await import(pathToFileURL(path.join(pkg, 'plugin/index.js'))), node = await import(pathToFileURL(path.join(pkg, 'plugin/node.js')));
const session = core.createIllustrator();
const image = await sharp(Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="80" height="80"><rect width="80" height="80" fill="white"/><circle cx="40" cy="40" r="25" fill="#245747"/></svg>')).png().toBuffer();
await node.traceInto(session, image, { label: 'Base', backdrop: { shape: 'squircle', style: 'glyph', color: '#C8643A', glyphColor: '#FFFFFF' } });
assert(session.context().layers.some(l => l.semantic === 'illustration.background'));
const styles = cli(['styles']); assert(styles.styles.some(s => s.id === 'funky-seasons')); assert(node.resolveStyle('Frutiger Aero').avoid.includes('Burbujas acuáticas'));
assert(typeof core.mountEditor === 'function');
const packText='canvas 100 24\nbackground none\ngroup pack { semantic ui.iconpack; group inicio { path techo { move 3 12; line 12 3; line 21 12; fill none; stroke #234 2 } } group buscar { at 40 0; circle aro { at 12 12; radius 7; fill none; stroke #234 2 } } }';
const protectedBase=core.createIllustrator({text:packText,selection:['pack.inicio']});
protectedBase.refine([{op:'set',target:'pack.inicio.techo',stroke:'#8855FF'}]);
assert.throws(()=>protectedBase.refine([{op:'delete',target:'pack.inicio'}]));
protectedBase.undo();assert.equal(protectedBase.getDocument().text,packText);
const archive=await node.exportIconArchive(packText,{sizes:[24,48]});assert.equal(archive.manifest.entries.length,2);assert.equal(archive.fileCount,9);
const packFile=path.join(dir,'pack.aru');await fs.writeFile(packFile,packText);
assert.equal(cli(['export-icons',packFile,'--out','icons.zip']).count,2);
assert(typeof core.prepareIconExports==='function');
assert.equal(core.listMaterials().length,5);
const materialBase=core.createIllustrator({text:packText,selection:['pack']});
materialBase.refine([{op:'material',target:'selection',preset:'chrome'}]);
assert(materialBase.svg().includes('gradientUnits="userSpaceOnUse"'));materialBase.undo();assert.equal(materialBase.getDocument().text,packText);
assert.equal(cli(['materials']).materials.length,5);
assert(cli(['material',packFile,'--select','pack','--style','fruits','--out','fruits.aru']).report.geometryPreserved);
const productionSession=core.createIllustrator(),job=node.createIconJob('Crea 25 iconos');let created=0;
const result=await node.produceIcons(productionSession,{job,transport:{run:async req=>{
  const count=Number(/EXACTLY (\d+)/.exec(req.prompt)[1]);
  const icons=Array.from({length:count},()=>{const i=created++;return {label:'Action '+i,purpose:'Distinct function '+i,aru:Array.from({length:9},(_,bit)=>`line p${bit} { from 4 ${3+bit*2}; to ${i&(1<<bit)?18:8} ${3+bit*2}; stroke #604631 1 }`).join('\n')};});
  return {ok:true,stdout:JSON.stringify({structured_output:{icons}})};
}}});
assert(result.report.complete);assert.equal(node.verifyIconJob(job,productionSession.getDocument().text),25);
productionSession.undo();assert.throws(()=>node.verifyIconJob(job,productionSession.getDocument().text));

console.log(JSON.stringify({ ok: true, consumer: dir, tests: ['installed-cli', 'invalid-batch-atomic', 'dry-run', 'preview', 'hash-conflict', 'stdin-json', 'opaque-png', 'browser-safe-entry', 'installed-node-reference-glyph', 'installed-style-catalog', 'installed-protected-refinement', 'installed-icon-zip-cli-api', 'installed-material-cli-api', 'installed-production-loop'] }, null, 2));
